LIBFCREPO-969. Bumped base Docker image to python:3.6.12-slim
Bumped base Docker image from python:3.6.2-slim to python:3.6.12-slim,
to correct the following error encountered when running "pip install" in
the Docker build:

```
Collecting cryptography>=2.3 (from jwcrypto->plastron==3.5.0.dev0)
  Downloading https://files.pythonhosted.org/packages/27/5a/007acee0243186123a55423d49cbb5c15cb02d76dd1b6a27659a894b13a2/cryptography-3.4.4.tar.gz (545kB)
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-svjpe0ah/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```

Also added a comment with a sample Docker build command, and updated
the README.md with instructions for the new Python version.

https://issues.umd.edu/browse/LIBFCREPO-969